name = input()
age = int(input())
weight = input()
height = input()

print ("\nNama Saya :", name)
print (f"Umur :{age} Tahun")
print (f"Berat Badan : {weight} Kg")
print (f"Tinggi Badan : {height} cm")
print(type(age))